export interface ISurvey {
  id: string;
  title: string;
  nickname: string;
  href: string;
}
// Generated by https://quicktype.io

export interface ISurveyWithDetails {
  title: string;
  nickname: string;
  language: string;
  folder_id: string;
  category: string;
  question_count: number;
  page_count: number;
  response_count: number;
  date_created: string;
  date_modified: string;
  id: string;
  buttons_text: ButtonsText;
  is_owner: boolean;
  footer: boolean;
  theme_id: string;
  custom_variables: { [key: string]: string };
  href: string;
  analyze_url: string;
  edit_url: string;
  collect_url: string;
  summary_url: string;
  preview: string;
}

export interface ButtonsText {
  next_button: string;
  prev_button: string;
  done_button: string;
  exit_button: string;
}
